"""empty message

Revision ID: 2d1ba03bc9cb
Revises: 73ddb30fb540
Create Date: 2021-03-23 20:23:10.975405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1ba03bc9cb'
down_revision = '73ddb30fb540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('git', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'git')
    # ### end Alembic commands ###
